# Generated by Django 3.0.7 on 2020-07-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Jhon', max_length=100)),
                ('lastname', models.CharField(default='Doe', max_length=120)),
                ('password', models.CharField(default='0000', max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('anfitrion', models.BooleanField(default=False)),
                ('location', models.CharField(default='bogota', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('phone', models.PositiveIntegerField(blank=True, default=1112223344)),
                ('active', models.BooleanField(default=True)),
                ('favorites', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, default='/media/rooms/pictures/user_profile.png', null=True, upload_to='users/pitures/', verbose_name='profile picture')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, default=999999)),
                ('nearest_places', models.CharField(max_length=120)),
                ('mts2', models.CharField(default='10mts2', max_length=120)),
                ('furniture', models.TextField(blank=True)),
                ('private_bath', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('closet', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('pet', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('furnish', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('couple', models.BooleanField(default=False)),
                ('family_atmosphere', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('picture', models.ImageField(blank=True, default='/media/rooms/pictures/photo.png', null=True, upload_to='media/rooms/pictures', verbose_name='room pictures')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quarto.User')),
            ],
        ),
    ]
