# Generated by Django 3.0.8 on 2020-08-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_room',
            name='id_room',
        ),
    ]
