# Generated by Django 3.0.8 on 2020-07-01 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0002_user_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='anfitrion',
            new_name='host',
        ),
    ]
