# Generated by Django 3.0.8 on 2020-07-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0003_auto_20200701_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='date',
        ),
    ]
