# Generated by Django 3.0.8 on 2020-07-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quarto', '0004_remove_room_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='/media/rooms/pictures/user_profile.png', null=True, upload_to='users/pictures/', verbose_name='profile picture'),
        ),
    ]
