language: python
python:
  - "3.7"
  
install:
  - pip install -r requirements.txt

script:
  - pytest test.py
  
git:
  depth: 3

branches:
  only:
  - master
  
notifications:
    email:
        recipients:
            - kasuru@hotmail.com
            - jaso_98@hotmail.com
        on_success: always
        on_failure: always

deploy:
    provider: heroku
    skip-cleanup: true
    keep-history: true
    api_key: 
        secure: ""

    app: #chart-covid
    on:
      repo: #Chart-Covid/backend
