# Generated by Django 3.1 on 2020-08-20 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images_Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='title',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='zip',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='bogota', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default=1112223344),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='/media/rooms/pictures/user_profile.png', null=True, upload_to='users/pitures/', verbose_name='profile picture'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, default=999999)),
                ('nearest_places', models.CharField(max_length=120)),
                ('mts2', models.CharField(default='10mts2', max_length=120)),
                ('furniture', models.TextField(blank=True)),
                ('private_bath', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('closet', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('pet', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('furnish', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('smoke', models.BooleanField(default=False)),
                ('couple', models.BooleanField(default=False)),
                ('family_atmosphere', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('id_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.images_room')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.favorites'),
        ),
    ]
