# Generated by Django 3.1 on 2020-08-21 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200820_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.images_room'),
        ),
    ]
